name: .NET

on:
  push:
    branches: [ jieun ]
  pull_request:
    branches: [ jieun ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - uses: actions/upload-artifact@v2
      with:
        path: path/to/artifact/world.txt
