name: .NET

on:
  push:
    branches: [ jieun ]
  pull_request:
    branches: [ master ]

env:
  GitHubPackageFeedUrl: https://nuget.pkg.github.com/AzureSprint2021/index.json
  LogicProjectPath: ${{ github.WORKSPACE }}/AnimalAdoption.Common.Logic
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      
        # Authenticates packages to push to GPR
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: ${{ env.GitHubPackageFeedUrl }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow

    - name: Package up project
      run: dotnet pack --configuration Release ${{ env.LogicProjectPath }}

    - name: Push package to GitHub registry
      run: dotnet nuget push ${{ env.LogicProjectPath }}/**/*.nupkg --skip-duplicate
      
    - name: Publish
      run: dotnet publish -c release -o /home/runner/work/AzureSprint02/AzureSprint02/test
    - name: Build
      run: dotnet build --no-restore
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: /home/runner/work/AzureSprint02/AzureSprint02/test/*
  
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Display structure of downloaded files
        run: ls -R
        
        #
        # Deploy to Azure Web apps
      - name: Run Azure
        uses: azure/webapps-deploy@v2
        with: 
          app-name: catHouse # Replace with your app name
          publish-profile: ${{ secrets.JIEUN_SECRET  }} # Define secret variable in repository settings as per action documentation
          #package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
          package: .
        

  
        
