# areum
name: .NET

on:
  push:
    branches: [ areum ]
  pull_request:
    branches: [ master ]
    
env:
  GitHubPackageFeedUrl: https://nuget.pkg.github.com/AzureSprint2021/index.json
  LogicProjectPath: ${{ github.WORKSPACE }}/AnimalAdoption.Common.Logic

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      
      # Authenticates packages to push to GPR
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: ${{ env.GitHubPackageFeedUrl }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow
    - name: Package up project
      run: dotnet pack --configuration Release ${{ env.LogicProjectPath }}
    - name: Push package to GitHub registry
      run: dotnet nuget push ${{ env.LogicProjectPath }}/**/*.nupkg --skip-duplicate
    - name: Build
      run: dotnet build --no-restore
      
    - name: Publish portal project in Release mode
      run: dotnet publish ${{ github.workspace }}\AnimalAdoption.Web.Portal\AnimalAdoption.Web.Portal.csproj --configuration Release --no-build --output ./taa-portal/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.3
      with:
        name: drop
        path:  ${{ github.workspace }}\taa-portal\
        if-no-files-found: error
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.5
      with:
        name: drop
        path: ./taa-portal/
        
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: wa-test-aueast-azsprintseries
        publish-profile: ${{ secrets.WA_TEST_AUEAST_AZSPRINTSERIES_PUBLISH_PROFILE }}
        package: ./taa-portal/


    
