# areum
name: .NET

on:
  push:
    branches: [ areum ]
  pull_request:
    branches: [ master ]
    
env:
  GitHubPackageFeedUrl: https://nuget.pkg.github.com/AzureSprint2021/index.json
  LogicProjectPath: ${{ github.WORKSPACE }}/AnimalAdoption.Common.Logic

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      
      # Authenticates packages to push to GPR
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: ${{ env.GitHubPackageFeedUrl }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow
    - name: Package up project
      run: dotnet pack --configuration Release ${{ env.LogicProjectPath }}
    - name: Push package to GitHub registry
      run: dotnet nuget push ${{ env.LogicProjectPath }}/**/*.nupkg --skip-duplicate
    - name: Build
      run: dotnet build --no-restore
    - name : Publish
      run : dotnet publish -c release -o ${{env.DOTNET_ROOT}}/areum

    - uses: actions/upload-artifact@v2
      with:
        name : areum_artifact
        path: ${{env.DOTNET_ROOT}}/areum
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: areum_artifact
      - name: Display structure of downloaded files
        run: ls -R
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: catHouse
          slot-name : production
          # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
          publish-profile: ${{secrets.AREUM_SECRET}}
          # Enter an existing Slot other than the Production slot
          # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
          package : .

    
