name: .NET

on:
  push :
    branches : [ master ]
  pull_request:
    branches: [ master ]
    
env:
  GitHubPackageFeedUrl: https://nuget.pkg.github.com/AzureSprint2021/index.json
  LogicProjectPath: ${{ github.WORKSPACE }}/AnimalAdoption.Common.Logic
  
jobs:
  build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow         
      - name: Package up project
        run: dotnet pack --configuration Release ${{ env.LogicProjectPath }}

      - name: Push package to GitHub registry
        run: dotnet nuget push ${{ env.LogicProjectPath }}/**/*.nupkg --skip-duplicate
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration release
      - name : test
        run : dotnet test --filter FullyQualifiedName\!~FunctionalTests
      - name: publish
        run: dotnet publish -c release -o ${{env.DOTNET_ROOT}}/masterArtifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          # Artifact name
          name: masterArtifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{env.DOTNET_ROOT}}/masterArtifact
          # The desired behavior if no files are found using the provided path.
      
